### ISSUE TITLE
Informations about the goal

### ISSUE THREAD

**Issue by Galixte** [BoardTools/updater#2]
Hi @lavigor,

this extension is only intended to update this extension: https://github.com/BoardTools/upload ?

**Comment by lavigor** [comment]
Yes.
I also had an idea to add the installation feature for the case if Upload Extensions is not installed yet.
But just for now the only purpose of this extension is safe updates of Upload Extensions without FTP.

**Comment by Galixte** [comment]
Thanks ;)
