### ISSUE TITLE
Please confirm that you upload the true extension zip file and try again.

### ISSUE THREAD

**Issue by wads24** [BoardTools/updater#3]
When I clicked "update"  to update Upload Extensions.....  I go the below error.

"The extension wasn’t uploaded. Please confirm that you upload the true extension zip file and try again."

Screenshot:  http://pichost.org/images/2019/01/04/Capture.jpg

**Comment by lavigor** [comment]
Hi, @wads24 
I've made the necessary fix, thank you for reporting the issue.
Please update the Updater to the latest commit.
